---
output: github_document
---

# `{sarcasm}`

## Usage

```{r setup, include = FALSE}
devtools::load_all()

library(reticulate)

knitr::knit_hooks$set(
    error = function(x, options) {
        paste0( "<pre><code><span style='color: red;'>", sarcastic(x), "<span></pre></code>")
    }
)

knitr::opts_chunk$set(comment = NULL)
```


Produces sArCaStic text from a character vector.

```{r}
set.seed(2)
text = 'pythonistas'
sarcastic(text)
```

```{r}
set.seed(2)
text = c('pythonistas', 'r_users')
sarcastic(text)
```

Comes with shorthand as well.

```{r}
text %>% `/s`
```

## Error handler

Make a mockery of those dreadful errors.

```{r err-handle, error=TRUE, message = FALSE}
sarcastic_errors()
A = rnorm
A[10]
```


## Installation

```r
remotes::install_github("https://github.com/awong234/sarcasm")
```

# Python module

There is also a python module included:

```{r}
pysnark = reticulate::import_from_path(module = 'sarcasm.sarcasm', path = 'pysnark/')
pysnark$sarcastic(text)
```

```{r}
pysnark$sarcastic(pysnark$sarcastic)
```

